#!/bin/bash

# 使用在线 API 生成图片
# 这个脚本使用各种免费图片生成 API

OUTPUT_DIR="/Users/victoryx/code/document/公众号写作/images/sleepless-agent"

echo "由于环境限制，我将为你提供几个方案："
echo ""
echo "方案 1: 使用 AI 图片生成服务"
echo "  - ChatGPT Plus 的 DALL-E 3"
echo "  - Midjourney"
echo "  - Stable Diffusion"
echo ""
echo "方案 2: 使用在线工具手动创建"
echo "  - Canva (canva.com)"
echo "  - Figma (figma.com)"
echo "  - Photopea (photopea.com - 免费 PS 替代)"
echo ""
echo "方案 3: 使用 macOS 自带的预览.app"
echo "  - 创建纯色背景图"
echo "  - 添加文字和形状"
echo ""
echo "=== 以下是每张图片的详细设计说明 ==="
echo ""
echo "----------------------------------------"
echo "图片 1: 01-main.jpg (封面图)"
echo "尺寸: 1920x1080"
echo "主题: Sleepless Agent 概念图"
echo ""
echo "设计元素:"
echo "- 背景: 深蓝/黑色渐变 (#0A0F1E 到 #050A19)"
echo "- 左侧: 月亮图标 + 睡眠的人形轮廓"
echo "- 右侧: 发光的 AI 核心（蓝色光晕）+ 代码流效果"
echo "- 底部中央: 大标题 'Sleepless Agent' 白色"
echo "- 标题下方: 副标题 '24/7 AI Development Team' 蓝色 (#64C8FF)"
echo ""
echo "视觉隐喻: 人类睡觉时 AI 继续工作"
echo "----------------------------------------"
echo ""
echo "----------------------------------------"
echo "图片 2: 02-multi-agent.jpg (多代理工作流)"
echo "尺寸: 1920x1080"
echo "主题: 三 Agent 协作流程"
echo ""
echo "设计元素:"
echo "- 背景: 深色渐变 (#0F1423 到 #080C1C)"
echo "- 顶部: 标题 'Three-Agent Workflow'"
echo "- 三个 Agent 框 (水平排列):"
echo "  1. PLANNER (橙色 #FF9632) - 分析任务 | 制定计划"
echo "  2. WORKER (绿色 #32C896) - 执行任务 | 编写代码"
echo "  3. EVALUATOR (蓝色 #6496FF) - 验证结果 | 质量检查"
echo "- 连接箭头: 从 Planner → Worker → Evaluator"
echo "- 底部说明: '协作流程：规划 → 执行 → 验证'"
echo "----------------------------------------"
echo ""
echo "----------------------------------------"
echo "图片 3: 03.5-quickstart.jpg (快速上手)"
echo "尺寸: 1920x1080"
echo "主题: 安装步骤指南"
echo ""
echo "设计元素:"
echo "- 背景: 深色渐变"
echo "- 顶部: 标题 'Quick Start Guide'"
echo "- 左侧: 8 个步骤 (带编号圆圈)"
echo "  1. Install Claude Code CLI"
echo "  2. Clone Sleepless Agent"
echo "  3. Install Python Dependencies"
echo "  4. Create GitHub Token"
echo "  5. Configure config.yaml"
echo "  6. Setup GitHub CLI"
echo "  7. Run First Task"
echo "  8. Start Daemon (Optional)"
echo "- 右侧: 提示框 (前置条件 + 完成时间)"
echo "----------------------------------------"
echo ""
echo "----------------------------------------"
echo "图片 4: 03-scenarios.jpg (适用场景)"
echo "尺寸: 1920x1080"
echo "主题: 使用场景分析"
echo ""
echo "设计元素:"
echo "- 背景: 深色"
echo "- 顶部: 标题 'When to Use Sleepless Agent'"
echo "- 左侧 (绿色主题 '✅ Great For'):"
echo "  - Side Projects"
echo "  - Technical Debt"
echo "  - Batch Tasks"
echo "  - Tools & Scripts"
echo "- 右侧 (红色主题 '❌ Not For'):"
echo "  - Enterprise Projects"
echo "  - High Interaction"
echo "  - Custom Logic"
echo "- 底部: 总结框"
echo "----------------------------------------"
echo ""
echo "----------------------------------------"
echo "图片 5: 04-conclusion.jpg (结尾图)"
echo "尺寸: 1920x1080"
echo "主题: 未来展望"
echo ""
echo "设计元素:"
echo "- 背景: 深色渐变 + 装饰性光点"
echo "- 中央: 大标题 'The Future of Development'"
echo "- 下方: 两行文字"
echo "  'AI isn't replacing you.'"
echo "  'It's becoming your team.'"
echo "- 分隔线"
echo "- 底部: 'You define requirements → AI builds → You review'"
echo "- GitHub 链接"
echo "----------------------------------------"
echo ""
echo "=== 推荐使用 ChatGPT + DALL-E 3 ==="
echo ""
echo "你可以用以下提示词在 ChatGPT 中生成："
echo ""
echo "For cover image (01-main.jpg):"
echo '"Create a tech illustration showing the concept of Sleepless Agent - an AI coding assistant that works 24/7. On the left side, show a sleeping person silhouette with a moon icon. On the right side, show a glowing AI robot/agent actively writing code on holographic screens with neon blue light. The AI has code streams flowing from it. Background is deep blue/black with subtle grid lines. Style: Dark tech aesthetic, cyberpunk-inspired but professional. The concept: While humans sleep, AI works. 16:9 aspect ratio. No text in image."'"
echo ""
echo "For multi-agent workflow (02-multi-agent.jpg):"
echo '"Create a technical diagram showing a three-agent workflow. Three boxes arranged horizontally with arrows connecting them. Box 1 (orange) labeled PLANNER with subtitle Task Analysis. Box 2 (green) labeled WORKER with subtitle Code Execution. Box 3 (blue) labeled EVALUATOR with subtitle Quality Check. Dark gradient background. Clean, professional tech aesthetic. Show the flow from left to right with arrows."'"
echo ""
echo "Or use Canva templates and customize."
